run:
  go: "1.17"
  timeout: 10m
  skip-files:
    - expt/main.go

output:
  format: colored-line-number

linters:
  enable-all: true
  disable:
    - decorder
    - exhaustruct
    - cyclop
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocyclo
    - godox
    - gofumpt
    - golint
    - interfacer
    - lll
    - maintidx
    - ireturn
    - maligned
    - nlreturn
    - nolintlint
    - prealloc
    - promlinter
    - scopelint
    - tagliatelle
    - testpackage
    - paralleltest
    - tparallel
    - containedctx
    - varnamelen
    - wrapcheck
    - wsl
    - forbidigo
    - gomnd

linters-settings:
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    disable-dec-order-check: false
    disable-init-func-first-check: false
  dupl:
    threshold: 100
  errcheck: # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    check-type-assertions: true
  goconst:
    min-len: 2 # Minimal length of string constant.
    min-occurrences: 2 # Minimum occurrences of constant string count to trigger issue.
    ignore-tests: true
    match-constant: false # Look for existing constants matching the values.
    numbers: true # Search also for duplicated numbers.
    min: 2 # Minimum value, only works with goconst.numbers
    max: 2 # Maximum value, only works with goconst.numbers
  revive:
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
    rules:
      - name: atomic
      - name: context-as-argument
      - name: context-keys-type
      - name: defer
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: increment-decrement
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: var-declaration
      - name: var-naming
  gomnd:
    ignored-numbers:
      - "0o600"
      - "0o644"
      - "0o655"
      - "0o666"
      - "0o770"
      - "0o755"
      - "0o765"
      - "0o777"
    ignored-functions:
      - "args.Error"
      - "strconv.ParseInt"
  gosimple:
    go: "1.17"
    checks:
      - "all"
  staticcheck:
    go: "1.17"
    checks:
      - "all"
  goimports:
    local-prefixes: github.com/odpf/dex
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/odpf/dex) # Groups all imports with the specified Prefix.
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
    enabled-tags:
      - diagnostic
  #      - style
  #      - opinionated
  #      - performance
  unparam:
    # Inspect exported functions.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    check-exported: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocritic
        - dupl
    - path: cli
      linters:
        - forbidigo
        - contextcheck
severity:
  default-severity: error
